window.dashboardData = {
  snapshot: {
    title: "Pass-wide snow snapshot",
    compiledOn: "March 24, 2026",
    sources: [
      {
        label: "Mountain Collective weather page",
        url: "https://mountaincollective.com/weather/"
      },
      {
        label: "OnTheSnow Mountain Collective snow report",
        url: "https://www.onthesnow.com/mountain-collective/skireport"
      }
    ],
    notes: [
      "Destination list is based on the official 2026/2027 Mountain Collective weather page.",
      "Current snow, forecast, base, trails, lifts, and freshness are from the OnTheSnow pass-wide Mountain Collective report.",
      "24h snowfall, 48h snowfall, and season snowfall are modeled in the UI but are not consistently available from the single pass-wide source."
    ]
  },
  resorts: [
    {
      id: "alta",
      name: "Alta Ski Area",
      region: "United States",
      country: "USA",
      hemisphere: "Northern",
      status: "Open",
      freshness: "11 hours ago",
      subResorts: [],
      officialConditionsUrl: "https://www.alta.com",
      mountainCollectiveUrl: "https://mountaincollective.com/weather/",
      sourceUrl: "https://www.onthesnow.com/mountain-collective/skireport",
      condition: null,
      snowfall24Hours: null,
      snowfall48Hours: null,
      snowfall72Hours: 0,
      snowfallForecast72Hours: 0,
      seasonSnowfall: null,
      baseDepthMin: 83,
      baseDepthMax: 83,
      trailsOpen: 82,
      trailsTotal: 118,
      liftsOpen: 5,
      liftsTotal: 8,
      notes: "72h snow is source-backed. 24h and 48h are not exposed by the pass-wide feed."
    },
    {
      id: "aspen",
      name: "Aspen Snowmass",
      region: "United States",
      country: "USA",
      hemisphere: "Northern",
      status: "Open",
      freshness: "2 hours ago",
      subResorts: ["Aspen Mountain", "Aspen Highlands", "Buttermilk", "Snowmass"],
      officialConditionsUrl: "https://www.aspensnowmass.com",
      mountainCollectiveUrl: "https://mountaincollective.com/weather/",
      sourceUrl: "https://www.onthesnow.com/mountain-collective/skireport",
      condition: "Spring Snow",
      snowfall24Hours: null,
      snowfall48Hours: null,
      snowfall72Hours: 0,
      snowfallForecast72Hours: 0,
      seasonSnowfall: null,
      baseDepthMin: 24,
      baseDepthMax: 48,
      trailsOpen: 233,
      trailsTotal: 366,
      liftsOpen: 30,
      liftsTotal: 41,
      notes: "Best tracked as one destination because the pass grants access across the Aspen Snowmass portfolio."
    },
    {
      id: "banff-sunshine",
      name: "Banff Sunshine",
      region: "Canada",
      country: "Canada",
      hemisphere: "Northern",
      status: "Open",
      freshness: "10 hours ago",
      subResorts: [],
      officialConditionsUrl: "https://www.skibanff.com",
      mountainCollectiveUrl: "https://mountaincollective.com/weather/",
      sourceUrl: "https://www.onthesnow.com/mountain-collective/skireport",
      condition: "Packed Powder",
      snowfall24Hours: null,
      snowfall48Hours: null,
      snowfall72Hours: 2,
      snowfallForecast72Hours: 9,
      seasonSnowfall: null,
      baseDepthMin: 104,
      baseDepthMax: 104,
      trailsOpen: 134,
      trailsTotal: 140,
      liftsOpen: 12,
      liftsTotal: 12,
      notes: ""
    },
    {
      id: "big-sky",
      name: "Big Sky Resort",
      region: "United States",
      country: "USA",
      hemisphere: "Northern",
      status: "Open",
      freshness: "4 hours ago",
      subResorts: [],
      officialConditionsUrl: "https://www.bigskyresort.com",
      mountainCollectiveUrl: "https://mountaincollective.com/weather/",
      sourceUrl: "https://www.onthesnow.com/mountain-collective/skireport",
      condition: null,
      snowfall24Hours: null,
      snowfall48Hours: null,
      snowfall72Hours: 0,
      snowfallForecast72Hours: 0,
      seasonSnowfall: null,
      baseDepthMin: 56,
      baseDepthMax: 56,
      trailsOpen: 132,
      trailsTotal: 320,
      liftsOpen: null,
      liftsTotal: null,
      notes: "The pass-wide report exposed terrain data but not lift counts for this snapshot."
    },
    {
      id: "bromont",
      name: "Bromont, montagne d'experiences",
      region: "Canada",
      country: "Canada",
      hemisphere: "Northern",
      status: "Open",
      freshness: "8 hours ago",
      subResorts: [],
      officialConditionsUrl: "https://www.bromontmontagne.com",
      mountainCollectiveUrl: "https://mountaincollective.com/weather/",
      sourceUrl: "https://www.onthesnow.com/mountain-collective/skireport",
      condition: "Machine Groomed",
      snowfall24Hours: null,
      snowfall48Hours: null,
      snowfall72Hours: 6,
      snowfallForecast72Hours: 2,
      seasonSnowfall: null,
      baseDepthMin: 31,
      baseDepthMax: 31,
      trailsOpen: 51,
      trailsTotal: 125,
      liftsOpen: 5,
      liftsTotal: 11,
      notes: ""
    },
    {
      id: "chamonix",
      name: "Chamonix Mont-Blanc",
      region: "Europe",
      country: "France",
      hemisphere: "Northern",
      status: "Open",
      freshness: "17 hours ago",
      subResorts: [],
      officialConditionsUrl: "https://en.chamonix.com",
      mountainCollectiveUrl: "https://mountaincollective.com/weather/",
      sourceUrl: "https://www.onthesnow.com/mountain-collective/skireport",
      condition: "Hard Packed",
      snowfall24Hours: null,
      snowfall48Hours: null,
      snowfall72Hours: 4,
      snowfallForecast72Hours: 18,
      seasonSnowfall: null,
      baseDepthMin: 94,
      baseDepthMax: 94,
      trailsOpen: 96,
      trailsTotal: 121,
      liftsOpen: 69,
      liftsTotal: 82,
      notes: ""
    },
    {
      id: "coronet-remarkables",
      name: "Coronet Peak + The Remarkables",
      region: "Southern Hemisphere",
      country: "New Zealand",
      hemisphere: "Southern",
      status: "Preseason",
      freshness: "Coronet Peak 6 months ago / The Remarkables 5 months ago",
      subResorts: ["Coronet Peak", "The Remarkables"],
      officialConditionsUrl: "https://www.nzski.com",
      mountainCollectiveUrl: "https://mountaincollective.com/weather/",
      sourceUrl: "https://www.onthesnow.com/mountain-collective/skireport",
      condition: null,
      snowfall24Hours: null,
      snowfall48Hours: null,
      snowfall72Hours: null,
      snowfallForecast72Hours: null,
      seasonSnowfall: null,
      baseDepthMin: null,
      baseDepthMax: null,
      trailsOpen: null,
      trailsTotal: null,
      liftsOpen: null,
      liftsTotal: null,
      notes: "The pass groups these New Zealand mountains as one destination. Coronet Peak is listed to open June 13, 2026, and The Remarkables is also listed to open June 13, 2026."
    },
    {
      id: "grand-targhee",
      name: "Grand Targhee Resort",
      region: "United States",
      country: "USA",
      hemisphere: "Northern",
      status: "Open",
      freshness: "10 hours ago",
      subResorts: [],
      officialConditionsUrl: "https://www.grandtarghee.com",
      mountainCollectiveUrl: "https://mountaincollective.com/weather/",
      sourceUrl: "https://www.onthesnow.com/mountain-collective/skireport",
      condition: "Machine Groomed",
      snowfall24Hours: null,
      snowfall48Hours: null,
      snowfall72Hours: 0,
      snowfallForecast72Hours: 0,
      seasonSnowfall: null,
      baseDepthMin: 88,
      baseDepthMax: 88,
      trailsOpen: 86,
      trailsTotal: 95,
      liftsOpen: 6,
      liftsTotal: 6,
      notes: ""
    },
    {
      id: "jackson-hole",
      name: "Jackson Hole Mountain Resort",
      region: "United States",
      country: "USA",
      hemisphere: "Northern",
      status: "Open",
      freshness: "14 hours ago",
      subResorts: [],
      officialConditionsUrl: "https://www.jacksonhole.com",
      mountainCollectiveUrl: "https://mountaincollective.com/weather/",
      sourceUrl: "https://www.onthesnow.com/mountain-collective/skireport",
      condition: "Spring Snow",
      snowfall24Hours: null,
      snowfall48Hours: null,
      snowfall72Hours: 0,
      snowfallForecast72Hours: 0,
      seasonSnowfall: null,
      baseDepthMin: 0,
      baseDepthMax: 85,
      trailsOpen: 89,
      trailsTotal: 141,
      liftsOpen: 13,
      liftsTotal: 13,
      notes: ""
    },
    {
      id: "lake-louise",
      name: "Lake Louise",
      region: "Canada",
      country: "Canada",
      hemisphere: "Northern",
      status: "Open",
      freshness: "10 hours ago",
      subResorts: [],
      officialConditionsUrl: "https://www.skilouise.com",
      mountainCollectiveUrl: "https://mountaincollective.com/weather/",
      sourceUrl: "https://www.onthesnow.com/mountain-collective/skireport",
      condition: "Machine Groomed",
      snowfall24Hours: null,
      snowfall48Hours: null,
      snowfall72Hours: 3,
      snowfallForecast72Hours: 0.5,
      seasonSnowfall: null,
      baseDepthMin: 98,
      baseDepthMax: 98,
      trailsOpen: 156,
      trailsTotal: 170,
      liftsOpen: 13,
      liftsTotal: 13,
      notes: ""
    },
    {
      id: "le-massif",
      name: "Le Massif de Charlevoix",
      region: "Canada",
      country: "Canada",
      hemisphere: "Northern",
      status: "Open",
      freshness: "8 hours ago",
      subResorts: [],
      officialConditionsUrl: "https://www.lemassif.com",
      mountainCollectiveUrl: "https://mountaincollective.com/weather/",
      sourceUrl: "https://www.onthesnow.com/mountain-collective/skireport",
      condition: "Variable Conditions",
      snowfall24Hours: null,
      snowfall48Hours: null,
      snowfall72Hours: 2,
      snowfallForecast72Hours: 4,
      seasonSnowfall: null,
      baseDepthMin: 30,
      baseDepthMax: 30,
      trailsOpen: 51,
      trailsTotal: 53,
      liftsOpen: 7,
      liftsTotal: 8,
      notes: ""
    },
    {
      id: "marmot",
      name: "Marmot Basin",
      region: "Canada",
      country: "Canada",
      hemisphere: "Northern",
      status: "Open",
      freshness: "13 hours ago",
      subResorts: [],
      officialConditionsUrl: "https://www.skimarmot.com",
      mountainCollectiveUrl: "https://mountaincollective.com/weather/",
      sourceUrl: "https://www.onthesnow.com/mountain-collective/skireport",
      condition: "Powder",
      snowfall24Hours: null,
      snowfall48Hours: null,
      snowfall72Hours: 1,
      snowfallForecast72Hours: 2,
      seasonSnowfall: null,
      baseDepthMin: 52,
      baseDepthMax: 52,
      trailsOpen: 91,
      trailsTotal: 91,
      liftsOpen: 7,
      liftsTotal: 7,
      notes: ""
    },
    {
      id: "megeve",
      name: "Megeve",
      region: "Europe",
      country: "France",
      hemisphere: "Northern",
      status: "Open",
      freshness: "17 hours ago",
      subResorts: [],
      officialConditionsUrl: "https://www.megeve-tourisme.fr",
      mountainCollectiveUrl: "https://mountaincollective.com/weather/",
      sourceUrl: "https://www.onthesnow.com/mountain-collective/skireport",
      condition: "Spring Snow",
      snowfall24Hours: null,
      snowfall48Hours: null,
      snowfall72Hours: 2,
      snowfallForecast72Hours: 12,
      seasonSnowfall: null,
      baseDepthMin: 20,
      baseDepthMax: 91,
      trailsOpen: 139,
      trailsTotal: 227,
      liftsOpen: 73,
      liftsTotal: 110,
      notes: ""
    },
    {
      id: "mt-buller",
      name: "Mt Buller",
      region: "Southern Hemisphere",
      country: "Australia",
      hemisphere: "Southern",
      status: "Preseason",
      freshness: "6 months ago",
      subResorts: [],
      officialConditionsUrl: "https://www.mtbuller.com.au",
      mountainCollectiveUrl: "https://mountaincollective.com/weather/",
      sourceUrl: "https://www.onthesnow.com/mountain-collective/skireport",
      condition: null,
      snowfall24Hours: null,
      snowfall48Hours: null,
      snowfall72Hours: null,
      snowfallForecast72Hours: null,
      seasonSnowfall: null,
      baseDepthMin: null,
      baseDepthMax: null,
      trailsOpen: null,
      trailsTotal: null,
      liftsOpen: null,
      liftsTotal: null,
      notes: "Mt Buller is listed to open June 06, 2026."
    },
    {
      id: "niseko",
      name: "Niseko United",
      region: "Asia",
      country: "Japan",
      hemisphere: "Northern",
      status: "Open",
      freshness: "5 hours ago",
      subResorts: ["Grand Hirafu", "Hanazono", "Niseko Village", "Annupuri"],
      officialConditionsUrl: "https://www.niseko.ne.jp",
      mountainCollectiveUrl: "https://mountaincollective.com/weather/",
      sourceUrl: "https://www.onthesnow.com/mountain-collective/skireport",
      condition: "Variable Conditions",
      snowfall24Hours: null,
      snowfall48Hours: null,
      snowfall72Hours: 0,
      snowfallForecast72Hours: 0,
      seasonSnowfall: null,
      baseDepthMin: 53,
      baseDepthMax: 99,
      trailsOpen: null,
      trailsTotal: 61,
      liftsOpen: 23,
      liftsTotal: 29,
      notes: "The pass-wide source reported total trails but not the open-trail count."
    },
    {
      id: "panorama",
      name: "Panorama Mountain Resort",
      region: "Canada",
      country: "Canada",
      hemisphere: "Northern",
      status: "Open",
      freshness: "15 hours ago",
      subResorts: [],
      officialConditionsUrl: "https://www.panoramaresort.com",
      mountainCollectiveUrl: "https://mountaincollective.com/weather/",
      sourceUrl: "https://www.onthesnow.com/mountain-collective/skireport",
      condition: "Variable Conditions",
      snowfall24Hours: null,
      snowfall48Hours: null,
      snowfall72Hours: 0.4,
      snowfallForecast72Hours: 0.4,
      seasonSnowfall: null,
      baseDepthMin: 13,
      baseDepthMax: 62,
      trailsOpen: 63,
      trailsTotal: 144,
      liftsOpen: 11,
      liftsTotal: 11,
      notes: ""
    },
    {
      id: "revelstoke",
      name: "Revelstoke Mountain Resort",
      region: "Canada",
      country: "Canada",
      hemisphere: "Northern",
      status: "Open",
      freshness: "10 hours ago",
      subResorts: [],
      officialConditionsUrl: "https://www.revelstokemountainresort.com",
      mountainCollectiveUrl: "https://mountaincollective.com/weather/",
      sourceUrl: "https://www.onthesnow.com/mountain-collective/skireport",
      condition: "Packed Powder",
      snowfall24Hours: null,
      snowfall48Hours: null,
      snowfall72Hours: 9,
      snowfallForecast72Hours: 1,
      seasonSnowfall: null,
      baseDepthMin: 119,
      baseDepthMax: 119,
      trailsOpen: 32,
      trailsTotal: 42,
      liftsOpen: 4,
      liftsTotal: 5,
      notes: ""
    },
    {
      id: "snowbasin",
      name: "Snowbasin",
      region: "United States",
      country: "USA",
      hemisphere: "Northern",
      status: "Closed",
      freshness: "1 day ago",
      subResorts: [],
      officialConditionsUrl: "https://www.snowbasin.com",
      mountainCollectiveUrl: "https://mountaincollective.com/weather/",
      sourceUrl: "https://www.onthesnow.com/mountain-collective/skireport",
      condition: null,
      snowfall24Hours: null,
      snowfall48Hours: null,
      snowfall72Hours: null,
      snowfallForecast72Hours: null,
      seasonSnowfall: null,
      baseDepthMin: null,
      baseDepthMax: null,
      trailsOpen: null,
      trailsTotal: null,
      liftsOpen: null,
      liftsTotal: null,
      notes: "Snowbasin appears in the current Mountain Collective pass list, but the latest pass-wide snow board showed it in the closed section when this snapshot was assembled."
    },
    {
      id: "snowbird",
      name: "Snowbird",
      region: "United States",
      country: "USA",
      hemisphere: "Northern",
      status: "Open",
      freshness: "15 hours ago",
      subResorts: [],
      officialConditionsUrl: "https://www.snowbird.com",
      mountainCollectiveUrl: "https://mountaincollective.com/weather/",
      sourceUrl: "https://www.onthesnow.com/mountain-collective/skireport",
      condition: "Machine Groomed",
      snowfall24Hours: null,
      snowfall48Hours: null,
      snowfall72Hours: 0,
      snowfallForecast72Hours: 0,
      seasonSnowfall: null,
      baseDepthMin: 77,
      baseDepthMax: 77,
      trailsOpen: 132,
      trailsTotal: 149,
      liftsOpen: 14,
      liftsTotal: 14,
      notes: ""
    },
    {
      id: "sugar-bowl",
      name: "Sugar Bowl Resort",
      region: "United States",
      country: "USA",
      hemisphere: "Northern",
      status: "Open",
      freshness: "14 hours ago",
      subResorts: [],
      officialConditionsUrl: "https://www.sugarbowl.com",
      mountainCollectiveUrl: "https://mountaincollective.com/weather/",
      sourceUrl: "https://www.onthesnow.com/mountain-collective/skireport",
      condition: "Machine Groomed",
      snowfall24Hours: null,
      snowfall48Hours: null,
      snowfall72Hours: 0,
      snowfallForecast72Hours: 0,
      seasonSnowfall: null,
      baseDepthMin: 10,
      baseDepthMax: 44,
      trailsOpen: 74,
      trailsTotal: 105,
      liftsOpen: 7,
      liftsTotal: 12,
      notes: ""
    },
    {
      id: "sugarloaf",
      name: "Sugarloaf",
      region: "United States",
      country: "USA",
      hemisphere: "Northern",
      status: "Open",
      freshness: "15 hours ago",
      subResorts: [],
      officialConditionsUrl: "https://www.sugarloaf.com",
      mountainCollectiveUrl: "https://mountaincollective.com/weather/",
      sourceUrl: "https://www.onthesnow.com/mountain-collective/skireport",
      condition: "Packed Powder",
      snowfall24Hours: null,
      snowfall48Hours: null,
      snowfall72Hours: 11,
      snowfallForecast72Hours: 2,
      seasonSnowfall: null,
      baseDepthMin: 20,
      baseDepthMax: 30,
      trailsOpen: 72,
      trailsTotal: 176,
      liftsOpen: 8,
      liftsTotal: 15,
      notes: ""
    },
    {
      id: "sun-peaks",
      name: "Sun Peaks Resort",
      region: "Canada",
      country: "Canada",
      hemisphere: "Northern",
      status: "Open",
      freshness: "14 hours ago",
      subResorts: [],
      officialConditionsUrl: "https://www.sunpeaksresort.com",
      mountainCollectiveUrl: "https://mountaincollective.com/weather/",
      sourceUrl: "https://www.onthesnow.com/mountain-collective/skireport",
      condition: "Machine Groomed",
      snowfall24Hours: null,
      snowfall48Hours: null,
      snowfall72Hours: 0,
      snowfallForecast72Hours: 1,
      seasonSnowfall: null,
      baseDepthMin: 57,
      baseDepthMax: 71,
      trailsOpen: 138,
      trailsTotal: 144,
      liftsOpen: 13,
      liftsTotal: 13,
      notes: ""
    },
    {
      id: "sun-valley",
      name: "Sun Valley",
      region: "United States",
      country: "USA",
      hemisphere: "Northern",
      status: "Open",
      freshness: "16 hours ago",
      subResorts: [],
      officialConditionsUrl: "https://www.sunvalley.com",
      mountainCollectiveUrl: "https://mountaincollective.com/weather/",
      sourceUrl: "https://www.onthesnow.com/mountain-collective/skireport",
      condition: "Spring Snow",
      snowfall24Hours: null,
      snowfall48Hours: null,
      snowfall72Hours: 0,
      snowfallForecast72Hours: 0,
      seasonSnowfall: null,
      baseDepthMin: 46,
      baseDepthMax: 74,
      trailsOpen: 120,
      trailsTotal: 124,
      liftsOpen: 12,
      liftsTotal: 17,
      notes: ""
    },
    {
      id: "sunday-river",
      name: "Sunday River",
      region: "United States",
      country: "USA",
      hemisphere: "Northern",
      status: "Open",
      freshness: "7 hours ago",
      subResorts: [],
      officialConditionsUrl: "https://www.sundayriver.com",
      mountainCollectiveUrl: "https://mountaincollective.com/weather/",
      sourceUrl: "https://www.onthesnow.com/mountain-collective/skireport",
      condition: "Machine Groomed",
      snowfall24Hours: null,
      snowfall48Hours: null,
      snowfall72Hours: 20,
      snowfallForecast72Hours: 1,
      seasonSnowfall: null,
      baseDepthMin: 20,
      baseDepthMax: 20,
      trailsOpen: 109,
      trailsTotal: 140,
      liftsOpen: null,
      liftsTotal: null,
      notes: "The pass-wide report exposed trails but not lift counts for this snapshot."
    },
    {
      id: "taos",
      name: "Taos Ski Valley",
      region: "United States",
      country: "USA",
      hemisphere: "Northern",
      status: "Open",
      freshness: "14 hours ago",
      subResorts: [],
      officialConditionsUrl: "https://www.skitaos.com",
      mountainCollectiveUrl: "https://mountaincollective.com/weather/",
      sourceUrl: "https://www.onthesnow.com/mountain-collective/skireport",
      condition: "Packed Powder",
      snowfall24Hours: null,
      snowfall48Hours: null,
      snowfall72Hours: 0,
      snowfallForecast72Hours: 0,
      seasonSnowfall: null,
      baseDepthMin: 19,
      baseDepthMax: 19,
      trailsOpen: 25,
      trailsTotal: 113,
      liftsOpen: 9,
      liftsTotal: 13,
      notes: ""
    },
    {
      id: "valle-nevado",
      name: "Valle Nevado",
      region: "Southern Hemisphere",
      country: "Chile",
      hemisphere: "Southern",
      status: "Preseason",
      freshness: "5 months ago",
      subResorts: [],
      officialConditionsUrl: "https://www.vallenevado.com/en/",
      mountainCollectiveUrl: "https://mountaincollective.com/weather/",
      sourceUrl: "https://www.onthesnow.com/mountain-collective/skireport",
      condition: null,
      snowfall24Hours: null,
      snowfall48Hours: null,
      snowfall72Hours: null,
      snowfallForecast72Hours: null,
      seasonSnowfall: null,
      baseDepthMin: null,
      baseDepthMax: null,
      trailsOpen: null,
      trailsTotal: null,
      liftsOpen: null,
      liftsTotal: null,
      notes: "Valle Nevado is listed to open June 12, 2026."
    },
    {
      id: "whiteface",
      name: "Whiteface Mountain Resort",
      region: "United States",
      country: "USA",
      hemisphere: "Northern",
      status: "Open",
      freshness: "11 hours ago",
      subResorts: [],
      officialConditionsUrl: "https://whiteface.com",
      mountainCollectiveUrl: "https://mountaincollective.com/weather/",
      sourceUrl: "https://www.onthesnow.com/mountain-collective/skireport",
      condition: "Hard Packed",
      snowfall24Hours: null,
      snowfall48Hours: null,
      snowfall72Hours: 0,
      snowfallForecast72Hours: 1,
      seasonSnowfall: null,
      baseDepthMin: 23,
      baseDepthMax: 39,
      trailsOpen: 73,
      trailsTotal: 95,
      liftsOpen: 10,
      liftsTotal: 11,
      notes: ""
    }
  ]
};
